name: server
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    defaults:
      run:
        working-directory: packages/server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
